### ISSUE TITLE
Bitbucket 5.0

### ISSUE THREAD

**Issue by kevinnorton** [Parallels/atlassian-restrict-branch-model#2]
will you be updating for Bitbucket 5.0

**Comment by atikhono** [comment]
Yes, I will. You should be able to run the add-on as is on 5.x even though it's listed as incompatible. The add-on uses a deprecated API which I want to remove in the next version, but I'm having troubles with my sdk setup for 5.0.x. I see they've released 5.1.x and I'm going to try that tonight.

**Comment by atikhono** [comment]
The update is released at Atlassian Marketplace
